# backend/render.yaml
services:
  - type: web
    name: visionsleuth-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p uploads
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4 --timeout-keep-alive 120
    envVars:
      - key: GCP_BUCKET_NAME
        value: crime-detection-data
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
    healthCheckPath: /health
    autoDeploy: true
